# Generated by Django 3.1.3 on 2021-03-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210309_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_roster',
            name='player',
        ),
        migrations.RemoveField(
            model_name='team_roster',
            name='team',
        ),
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player_game_scoreboard',
            name='game',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player_game_scoreboard',
            name='player',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player_game_scoreboard',
            name='team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='game_team_score',
        ),
        migrations.DeleteModel(
            name='team',
        ),
        migrations.DeleteModel(
            name='team_roster',
        ),
    ]
