# Generated by Django 3.1.3 on 2021-03-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210322_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_game_scoreboard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
