# Generated by Django 3.1.3 on 2021-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_player_game_scoreboard_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_game_scoreboard',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
