# Generated by Django 3.1.3 on 2021-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20210323_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_game_scoreboard',
            name='game',
            field=models.IntegerField(default=None),
        ),
    ]
